# Generated by Django 5.2.14 on 2026-06-20 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motos', to='moto.categoria'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='moto.marca'),
        ),
    ]
