# Generated by Django 5.2.14 on 2026-06-20 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_moto_categoria_alter_moto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('ubicacion_bodega', models.CharField(blank=True, max_length=100)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='moto.moto')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='moto.sucursal')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'db_table': 'inventario',
                'unique_together': {('moto', 'sucursal')},
            },
        ),
        migrations.CreateModel(
            name='SucursalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_sucursal', to='moto.staff')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_asignado', to='moto.sucursal')),
            ],
            options={
                'verbose_name': 'Asignación de Staff a Sucursal',
                'verbose_name_plural': 'Asignaciones de Staff a Sucursal',
                'db_table': 'sucursal_staff',
                'unique_together': {('staff', 'sucursal')},
            },
        ),
    ]
