# Generated by Django 5.2 on 2026-06-17 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0002_categoria_marca_repuesto'),
        ('moto', '0002_proveedor_sucursal_direccion'),
    ]

    operations = [
    ]
