# Generated by Django 5.2 on 2026-06-22 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0004_compra_detallecompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_financiado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financiamientos', to='moto.venta')),
            ],
            options={
                'verbose_name': 'Financiamiento',
                'verbose_name_plural': 'Financiamientos',
                'db_table': 'financiamientos',
            },
        ),
        migrations.CreateModel(
            name='CuotaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='moto.financiamiento')),
            ],
            options={
                'verbose_name': 'Cuota de Pago',
                'verbose_name_plural': 'Cuotas de Pago',
                'db_table': 'cuotas_pago',
                'ordering': ['financiamiento', 'numero_cuota'],
            },
        ),
    ]
