# Generated by Django 5.2 on 2026-06-22 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0005_financiamiento_cuotapago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamiento',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financiamiento', to='moto.venta'),
        ),
        migrations.AddConstraint(
            model_name='cuotapago',
            constraint=models.UniqueConstraint(fields=('financiamiento', 'numero_cuota'), name='unique_cuota_por_financiamiento'),
        ),
    ]
