# Generated by Django 5.2.14 on 2026-06-22 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0005_historialprecio_resena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to='moto.staff'),
        ),
    ]
