# Generated by Django 5.2.7 on 2026-06-23 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0006_remove_moto_stock_alter_venta_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=100)),
                ('datos_antes', models.JSONField(blank=True, null=True)),
                ('datos_despues', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
