# Generated by Django 5.2.7 on 2026-06-23 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0006_alter_financiamiento_venta_and_more'),
        ('moto', '0007_logsactividad'),
    ]

    operations = [
    ]
