# Generated by Django 5.2 on 2026-06-23 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0008_merge_20260622_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garantia',
            name='posventa',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='posventa',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='tipo_cobertura',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_programada',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha_realizacion',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='mantenimiento',
            name='tipo_mantenimiento',
        ),
        migrations.AddField(
            model_name='garantia',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='garantia',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='moto.venta'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='moto.cliente'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='moto.moto'),
        ),
        migrations.DeleteModel(
            name='Posventa',
        ),
    ]
