# Generated by Django 5.2 on 2026-06-23 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0009_remove_garantia_posventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garantia',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='garantia',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='moto.venta'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='moto.cliente'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
