# Generated by Django 5.2 on 2026-06-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0010_alter_garantia_tipo_alter_garantia_venta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=100)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='moto.cliente')),
            ],
            options={
                'verbose_name': 'Historial de Cliente',
                'verbose_name_plural': 'Historiales de Clientes',
                'db_table': 'historial_cliente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionesCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='moto.cliente')),
            ],
            options={
                'verbose_name': 'Notificación de Cliente',
                'verbose_name_plural': 'Notificaciones de Clientes',
                'db_table': 'notificaciones_cliente',
                'ordering': ['-fecha'],
            },
        ),
    ]
