# Generated by Django 5.2.14 on 2026-07-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0012_alter_resena_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
