# Generated by Django 5.2.14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0013_moto_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsactividad',
            name='datos_antes',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='logsactividad',
            name='datos_despues',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]