# Generated by Django 5.2.14 on 2026-07-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0014_alter_logsactividad_datos_antes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
