# Generated by Django 5.2.14 on 2026-07-13 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0014_alter_logsactividad_datos_antes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='moto.cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='moto.moto')),
            ],
            options={
                'verbose_name': 'Favorito',
                'verbose_name_plural': 'Favoritos',
                'db_table': 'favoritos',
                'ordering': ['-fecha'],
                'unique_together': {('cliente', 'moto')},
            },
        ),
    ]