# Generated by Django 5.2.14 on 2026-07-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0015_favorito'),
        ('moto', '0015_sucursal_latitud_sucursal_longitud'),
    ]

    operations = [
    ]
