# Generated by Django 6.0.7 on 2026-07-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0016_merge_20260713_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='activo', max_length=20),
        ),
    ]