# Generated by Django 6.0.7 on 2026-07-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0017_financiamiento_estado_pendiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamiento',
            name='tasa_interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]