# Generated by Django 5.2.14 on 2026-07-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0018_financiamiento_tasa_interes_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moto',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='moto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
    ]
